revert _everything

diff --git a/.github/actions/setup-k8s-charm/action.yml b/.github/actions/setup-k8s-charm/action.yml
--- a/.github/actions/setup-k8s-charm/action.yml
+++ b/.github/actions/setup-k8s-charm/action.yml
@@ -23,6 +23,9 @@ inputs:
       - latest/stable
       - latest/beta
       - latest/edge
+  dashboard-charm-ref:
+    description: Git reference to use when cloning charm repository.
+    required: false
 
 runs:
   using: "composite"
@@ -37,28 +40,64 @@ runs:
           echo 'build_type=dashboard-resource' >> "$GITHUB_ENV"
         else
           # Build dashboard from source.
-          echo 'build_type=source' >> "$GITHUB_ENV"
+          echo 'build_type=checkout' >> "$GITHUB_ENV"
         fi
       shell: bash
+    - name: Check out Juju Dashboard charm
+      if: ${{ env.build_type == 'checkout' || env.build_type == 'dashboard-resource' }}
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ inputs.dashboard-charm-ref }}
+        repository: canonical/juju-dashboard-charm
+        path: juju-dashboard-charm
     - name: Set up Juju Dashboard release
-      if: ${{ env.build_type == 'source' }}
+      if: ${{ env.build_type == 'checkout' }}
       uses: actions/checkout@v4
       with:
         ref: ${{ inputs.dashboard-ref }}
         path: juju-dashboard-release
-    - name: Get the image and build the charm
-      id: dashboard-image
-      if: ${{ env.build_type != 'charm-release' }}
+    - name: Build Juju Dashboard image
+      if: ${{ env.build_type == 'checkout' }}
       shell: bash
       run: |
-        "${{ github.workspace }}/charms/k8s-charm/build.sh" \
-          "${{ env.build_type }}" \
-          "${{ inputs.dashboard-resource }}" \
-          >> "$GITHUB_OUTPUT"
-    - name: Import dashboard image to microK8s
-      if: ${{ env.build_type == 'source' }}
+        cd '${{ github.workspace }}/juju-dashboard-release'
+        DOCKER_BUILDKIT=1 docker build -t juju-dashboard:local .
+        docker image save juju-dashboard:local | sudo microk8s ctr image import -
+    - name: Choose dashboard image
+      id: dashboard-image
       shell: bash
-      run: docker image save juju-dashboard:local | sudo microk8s ctr image import -
+      if: ${{ env.build_type == 'checkout' || env.build_type == 'dashboard-resource' }}
+      run: |
+        case '${{ env.build_type }}' in
+          'checkout')
+            ID='juju-dashboard:local'
+          ;;
+          'dashboard-resource')
+            ID='canonicalwebteam/juju-dashboard:${{ inputs.dashboard-resource }}'
+          ;;
+        esac
+        echo "id=$ID" >> "$GITHUB_OUTPUT"
+    - name: Install charmcraft
+      if: ${{ env.build_type != 'charm-release' }}
+      run: sudo snap install charmcraft --classic
+      shell: bash
+    - name: Wait for charmcraft snap
+      if: ${{ env.build_type != 'charm-release' }}
+      uses: ./.github/actions/wait-for-snap
+      with:
+        snap: charmcraft
+    - name: Build the charm
+      if: ${{ env.build_type != 'charm-release' }}
+      uses: nick-fields/retry@v3
+      with:
+        timeout_minutes: 10
+        max_attempts: 3
+        command: |
+          # This command is retired as it sometimes fails with the following error:.
+          # Failed to wait for snap refreshes to complete.
+          # error: daemon is stopping to wait for socket activation
+          cd ${{ github.workspace }}/juju-dashboard-charm/k8s-charm
+          charmcraft pack
     - name: Switch to controller
       run: juju switch '${{ inputs.controller-model }}'
       shell: bash
@@ -68,7 +107,7 @@ runs:
       shell: bash
     - name: Deploy built charm
       if: ${{ env.build_type != 'charm-release' }}
-      run: juju deploy ${{ github.workspace }}/charms/k8s-charm/juju-dashboard*.charm dashboard --resource 'dashboard-image=${{ steps.dashboard-image.outputs.id }}'
+      run: juju deploy ${{ github.workspace }}/juju-dashboard-charm/k8s-charm/juju-dashboard*.charm dashboard --resource 'dashboard-image=${{ steps.dashboard-image.outputs.id }}'
       shell: bash
     - name: Integrate charm
       run: juju integrate '${{ inputs.controller-app }}' dashboard
@@ -91,5 +130,6 @@ runs:
     - name: Clean up
       run: |
         # Delete build files to save space. Pass `|| true` so that an error is not thrown if the directories don't exist.
+        rm -rf '${{ github.workspace }}/juju-dashboard-charm' || true
         rm -rf '${{ github.workspace }}/juju-dashboard-release' || true
       shell: bash
diff --git a/.github/actions/setup-machine-charm/action.yml b/.github/actions/setup-machine-charm/action.yml
--- a/.github/actions/setup-machine-charm/action.yml
+++ b/.github/actions/setup-machine-charm/action.yml
@@ -18,6 +18,9 @@ inputs:
       - latest/stable
       - latest/beta
       - latest/edge
+  dashboard-charm-ref:
+    description: Git reference to use when cloning charm repository.
+    required: false
   controller-app:
     required: false
     description: The Juju controller application.
@@ -43,16 +46,53 @@ runs:
           echo 'build_type=bundled-dashboard' >> "$GITHUB_ENV"
         else
           # Build dashboard from source.
-          echo 'build_type=source' >> "$GITHUB_ENV"
+          echo 'build_type=checkout' >> "$GITHUB_ENV"
         fi
       shell: bash
-    - name: Set up Juju Dashboard release
+    - name: Check out Juju Dashboard charm
       if: ${{ env.build_type != 'charm-release' }}
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ inputs.dashboard-charm-ref }}
+        repository: canonical/juju-dashboard-charm
+        path: juju-dashboard-charm
+    - name: Set up Juju Dashboard release with specified version
+      if: ${{ env.build_type == 'dashboard-version' }}
+      run: |
+        cd '${{ github.workspace }}/juju-dashboard-charm'
+        ./scripts/update-machine-charm-dashboard.sh '${{ inputs.dashboard-version }}'
+      shell: bash
+    - name: Build Juju Dashboard for release
+      if: ${{ env.build_type == 'checkout' }}
       shell: bash
       run: |
-        "${{ github.workspace }}/charms/machine-charm/build.sh" \
-          "${{ env.build_type }}" \
-          "${{ inputs.dashboard-version }}"
+        cd '${{ github.workspace }}'
+        yarn install
+        yarn build
+        cd '${{ github.workspace }}/juju-dashboard-charm/machine-charm'
+        rm -rf src/dist/*
+        cp -r ${{ github.workspace }}/build/* src/dist
+    - name: Install charmcraft
+      if: ${{ env.build_type != 'charm-release' }}
+      run: sudo snap install charmcraft --classic
+      shell: bash
+    - name: Wait for charmcraft snap
+      if: ${{ env.build_type != 'charm-release' }}
+      uses: ./.github/actions/wait-for-snap
+      with:
+        snap: charmcraft
+    - name: Build the charm
+      if: ${{ env.build_type != 'charm-release' }}
+      uses: nick-fields/retry@v3
+      with:
+        timeout_minutes: 10
+        max_attempts: 3
+        command: |
+          # This command is retired as it sometimes fails with the following error:.
+          # Failed to wait for snap refreshes to complete.
+          # error: daemon is stopping to wait for socket activation
+          cd '${{ github.workspace }}/juju-dashboard-charm/machine-charm'
+          charmcraft pack
     - name: Switch to controller
       run: juju switch '${{ inputs.controller-model }}'
       shell: bash
@@ -62,7 +102,7 @@ runs:
       shell: bash
     - name: Deploy built charm
       if: ${{ env.build_type != 'charm-release' }}
-      run: juju deploy ${{ github.workspace }}/charms/machine-charm/juju-dashboard*.charm dashboard
+      run: juju deploy ${{ github.workspace }}/juju-dashboard-charm/machine-charm/juju-dashboard*.charm dashboard
       shell: bash
     - name: Integrate charm
       run: juju integrate '${{ inputs.controller-app }}' dashboard
@@ -75,4 +115,9 @@ runs:
         command: juju wait-for application dashboard
     - name: Disable analytics
       run: juju config dashboard analytics-enabled=false
+      shell: bash
+    - name: Clean up
+      run: |
+        # Delete build files to save space. Pass `|| true` so that an error is not thrown if the directories don't exist.
+        rm -rf '${{ github.workspace }}/juju-dashboard-charm' || true
       shell: bash
